Repository AIOCodeBase/AutomateNow, pull requests merged in 2025-10, with the labels that each got.

#15 Create Template.md
  Automation Scripts/Alibaba Cloud/Template.md
Labels: enhancement, hacktoberfest

#16 Create Template.md
  Automation Scripts/AWS/Template.md
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#17 Create Template.md
  Automation Scripts/Azure/Template.md
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#18 Create Template.md
  Automation Scripts/Google Cloud/Template.md
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#20 Create Template.md
  Automation Scripts/MacOS/Template.md
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#27 Create Rename a File
  Automation Scripts/Windows/Rename a File
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#44 Create Shutdown Computer
  Automation Scripts/Windows/Shutdown Computer
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#45 Create Restart Computer
  Automation Scripts/Windows/Restart Computer
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#46 Create Log Off Current User
  Automation Scripts/Windows/Log Off Current User
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#47 Create Open a Website
  Automation Scripts/Windows/Open a Website
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#51 Create Create a Text File
  Automation Scripts/Windows/Create a Text File
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#52 Create Append Text to a File
  Automation Scripts/Windows/Append Text to a File
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#67 Create Defragment a Drive
  Automation Scripts/Windows/Defragment a Drive
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#71 Create UnHide a File
  Automation Scripts/Windows/UnHide a File
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#74 Create Remove Read-Only Attribute
  Automation Scripts/Windows/Remove Read-Only Attribute
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#78 Create Disable Windows Firewall
  Automation Scripts/Windows/Disable Windows Firewall
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#80 Update Copy Files from One Folder to Another
  Automation Scripts/Windows/Copy Files from One Folder to Another
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#113 Create Export System Information to Text File
  Automation Scripts/Windows/Export System Information to Text File
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#115 Create Close All Running Applications
  Automation Scripts/Windows/Close All Running Applications
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#117 Create Create Multiple Folders
  Automation Scripts/Windows/Create Multiple Folders
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#119 Create Install a Software Package
  Automation Scripts/Windows/Install a Software Package
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#122 Create Toggle Dark-Light Mode
  Automation Scripts/Windows/Toggle Dark-Light Mode
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#126 Create Change Default Printer
  Automation Scripts/Windows/Change Default Printer
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#127 Create Cleanup Old Downloads
  Automation Scripts/Windows/Cleanup Old Downloads
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#128 Create Toggle Touchpad On-Off
  Automation Scripts/Windows/Toggle Touchpad On-Off
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#130 Create Change Screen Resolution
  Automation Scripts/Windows/Change Screen Resolution
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#132 Create Toggle Bluetooth On-Off
  Automation Scripts/Windows/Toggle Bluetooth On-Off
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#133 Create Delete Duplicate Files
  Automation Scripts/Windows/Delete Duplicate Files
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#134 Create Change Power Plan Settings
  Automation Scripts/Windows/Change Power Plan Settings
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#139 Create Change Default Browser
  Automation Scripts/Windows/Change Default Browser
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#140 Create Export Event Logs
  Automation Scripts/Windows/Export Event Logs
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#141 Create Toggle Windows Features On-Off
  Automation Scripts/Windows/Toggle Windows Features On-Off
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#180 Create clean_logs
  Automation Scripts/Linux/clean_logs
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#182 Create find_large_files
  Automation Scripts/Linux/find_large_files
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#183 Create check_internet
  Automation Scripts/Linux/check_internet
Labels: hacktoberfest, hacktoberfest-accepted

#185 Create monitor_disk
  Automation Scripts/Linux/monitor_disk
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#186 Create git_auto_commit
  Automation Scripts/Linux/git_auto_commit
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#191 Create check_processes
  Automation Scripts/Linux/check_processes
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#192 Create ssh_login
  Automation Scripts/Linux/ssh_login
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#194 Create download_file
  Automation Scripts/Linux/download_file
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#195 Create check_permissions
  Automation Scripts/Linux/check_permissions
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#196 Create Automate User Creation
  Automation Scripts/Linux/create_user
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#197 Create encrypt_file
  Automation Scripts/Linux/encrypt_file
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#198 Create decrypt_file
  Automation Scripts/Linux/decrypt_file
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#200 Create rotate_logs
  Automation Scripts/Linux/rotate_logs
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#201 Create network_scan
  Automation Scripts/Linux/network_scan
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#202 Create sync_files
  Automation Scripts/Linux/sync_files
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#205 Create reboot_system
  Automation Scripts/Linux/reboot_system
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#206 Create install_package
  Automation Scripts/Linux/install_package
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#208 Create delete_user
  Automation Scripts/Linux/delete_user
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#210 Create extract_file
  Automation Scripts/Linux/extract_file
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#211 Create system_info
  Automation Scripts/Linux/system_info
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#215 Create cleanup_system
  Automation Scripts/Linux/cleanup_system
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#216 Create block_ip
  Automation Scripts/Linux/block_ip
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#264 Create backup_docker
  Automation Scripts/Linux/backup_docker
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#267 Create speed_test
  Automation Scripts/Linux/speed_test
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#268 Create reset_password
  Automation Scripts/Linux/reset_password
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#270 Create search_file
  Automation Scripts/Linux/search_file
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#272 Create analyze_logs
  Automation Scripts/Linux/analyze_logs
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#277 Create check_interface
  Automation Scripts/Linux/check_interface
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#286 Create sync_time
  Automation Scripts/Linux/sync_time
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#287 Create convert_encoding
  Automation Scripts/Linux/convert_encoding
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#289 Create reboot_on_load
  Automation Scripts/Linux/reboot_on_load
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#321 Create ssh_brute_force_protect
  Automation Scripts/Linux/ssh_brute_force_protect
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#323 Create check_cert_expiry
  Automation Scripts/Linux/check_cert_expiry
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#328 Create monitor_network_traffic
  Automation Scripts/Linux/monitor_network_traffic
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#329 Create check_file_integrity
  Automation Scripts/Linux/check_file_integrity
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#330 Create log_user_activity
  Automation Scripts/Linux/log_user_activity
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#332 Create archive_logs
  Automation Scripts/Linux/archive_logs
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#333 Create distribute_ssh_key
  Automation Scripts/Linux/distribute_ssh_key
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#334 Create security_audit
  Automation Scripts/Linux/security_audit
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#335 Create encrypt_with_gpg
  Automation Scripts/Linux/encrypt_with_gpg
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#343 Create restrict_user_login
  Automation Scripts/Linux/restrict_user_login
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#344 Create firewall_log_analysis
  Automation Scripts/Linux/firewall_log_analysis
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#346 Create update_timezone
  Automation Scripts/Linux/update_timezone
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#348 Create load_kernel_module
  Automation Scripts/Linux/load_kernel_module
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#350 Create check_service_dependency
  Automation Scripts/Linux/check_service_dependency
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#364 Create upload_to_s3
  Automation Scripts/AWS/upload_to_s3
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#366 Create start_ec2_instance
  Automation Scripts/AWS/start_ec2_instance
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#369 Create list_iam_users
  Automation Scripts/AWS/list_iam_users
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#370 Create create_iam_user
  Automation Scripts/AWS/create_iam_user
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#371 Create list_lambda_functions
  Automation Scripts/AWS/list_lambda_functions
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#378 feat: add linux bash script to delete folder
  Automation Scripts/Linux/delete_folder
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#376 feat: management docker in linux
  Automation Scripts/Linux/stop_docker
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
